### ISSUE TITLE
How is this different from passport-reddit?

### ISSUE THREAD

**Issue by cedricium** [ghaiklor/passport-reddit-token#136]
Hi, new to passport.js and authentication in general, so I was just wondering how this strategy differs from the [passport-reddit](http://www.passportjs.org/packages/passport-reddit/) strategy?

I'm currently working on a project which requires users to authenticate with their Reddit accounts. I'm interested in seeing if either of these strategies would fit my use-case.

**Comment by ghaiklor** [comment]
`passport-reddit-token` does not use OAuth flow for authentication, it uses already got token to parse the profile, while `passport-reddit` provides you with an OAuth flow.
